-- =====================================================================
-- SmartRent B2B — schema inicial (Modelo Físico)
--
-- Gerado a partir das entidades JPA pelo SchemaGenerator, em modo
-- scripts-only do Hibernate com dialeto PostgreSQL e sem conexão com
-- banco. Para regerar após alterar o mapeamento:
--
--     ./mvnw -Pschema-gen process-test-classes
--     # depois compare target/schema-postgres.sql com este arquivo
--
-- Migrations já aplicadas NUNCA devem ser editadas: crie um V2__ com a
-- alteração, senão o checksum do Flyway quebra em quem já rodou a V1.
-- =====================================================================


create table imoveis (
    id bigint generated by default as identity,
    ativo boolean not null,
    capacidade_hospedes integer not null,
    data_cadastro timestamp(6) not null,
    descricao TEXT,
    bairro varchar(100) not null,
    cep varchar(9) not null,
    cidade varchar(100) not null,
    complemento varchar(100),
    estado varchar(2) not null,
    latitude numeric(10,7) not null,
    logradouro varchar(150) not null,
    longitude numeric(10,7) not null,
    numero varchar(20),
    numero_banheiros integer not null,
    numero_quartos integer not null,
    tipo_imovel varchar(20) not null check (tipo_imovel in ('APARTAMENTO','CASA','KITNET','POUSADA','CHALE','LOFT','OUTRO')),
    titulo varchar(150) not null,
    valor_diaria_base numeric(10,2) not null,
    usuario_id bigint not null,
    primary key (id)
);

create table imovel_comodidades (
    imovel_id bigint not null,
    comodidade varchar(60)
);

create table reservas (
    id bigint generated by default as identity,
    data_checkin date not null,
    data_checkout date not null,
    data_criacao timestamp(6) not null,
    hospede_email varchar(150) not null,
    hospede_nome varchar(120) not null,
    hospede_telefone varchar(20),
    observacoes TEXT,
    origem varchar(20) not null check (origem in ('DIRETA','AIRBNB','BOOKING','OUTRA_OTA')),
    status varchar(20) not null check (status in ('PENDENTE','CONFIRMADA','CANCELADA','CONCLUIDA')),
    valor_total numeric(10,2) not null,
    versao bigint,
    imovel_id bigint not null,
    primary key (id)
);

create table sugestoes_preco (
    id bigint generated by default as identity,
    data_geracao timestamp(6) not null,
    data_referencia date not null,
    fator_microgeografia numeric(5,2),
    fator_sazonalidade numeric(5,2),
    justificativa_ia TEXT,
    modelo_ia_utilizado varchar(80),
    origem_calculo varchar(30) not null check (origem_calculo in ('IA_GENERATIVA','FALLBACK_REGRA_NEGOCIO')),
    percentual_ajuste numeric(5,2),
    valor_base numeric(10,2) not null,
    valor_sugerido numeric(10,2) not null,
    imovel_id bigint not null,
    primary key (id)
);

create table usuarios (
    id bigint generated by default as identity,
    ativo boolean not null,
    data_criacao timestamp(6) not null,
    email varchar(150) not null unique,
    nome varchar(120) not null,
    papel varchar(20) not null check (papel in ('ADMIN','ANFITRIAO')),
    senha_hash varchar(60) not null,
    telefone varchar(20),
    primary key (id)
);

create index idx_imoveis_usuario 
   on imoveis (usuario_id);

create index idx_imoveis_ativo 
   on imoveis (ativo);

create index idx_reservas_imovel 
   on reservas (imovel_id);

create index idx_reservas_periodo 
   on reservas (imovel_id, data_checkin, data_checkout);

create index idx_sugestoes_imovel_data 
   on sugestoes_preco (imovel_id, data_referencia);

alter table if exists imoveis 
   add constraint fk_imovel_usuario 
   foreign key (usuario_id) 
   references usuarios;

alter table if exists imovel_comodidades 
   add constraint fk_comodidade_imovel 
   foreign key (imovel_id) 
   references imoveis;

alter table if exists reservas 
   add constraint fk_reserva_imovel 
   foreign key (imovel_id) 
   references imoveis;

alter table if exists sugestoes_preco 
   add constraint fk_sugestao_imovel 
   foreign key (imovel_id) 
   references imoveis;
